/**
 * 商家管理系统api
 */

export default [
{ name: '获取商家分类', method: 'getDealerclassify', path: 'm2c.scm/dealerclassify/sys/tree', type: 'get'},
{ name: '获取商家列表', method: 'getDealerList', path: 'm2c.scm/dealer/sys/list',type: 'get'},
{ name: '获取业务员列表', method: 'getSalesmanList', path: 'm2c.scm/seller/sys',type: 'get'},
{ name: '业务员离职（禁用）', method: 'turnOffPermissions',path: 'm2c.scm/admin/seller/disable', type: 'put'},
{ name: '生成业务员Id', method: 'getSalesmanId', path: 'm2c.scm/seller/sys/id',type: 'get'},
{ name: '新增/编辑 业务员信息', method: 'saveSalesmanInfo', path: 'm2c.scm/seller/sys/mng',type: 'get'},
{ name: '获取收支明细',method: 'orderStore', path: 'm2c.trading/web/accounting/dealer/manager/inout/detail/page', type: 'get'},
{ name: '获取资金概况列表', method: 'amountList', path: 'm2c.trading/web/account/dealer/admin/amountList.web',type: 'get'},
{ name: '获取资金概况', method: 'amount', path: 'm2c.trading/web/account/dealer/admin/amount.web',type: 'get'},
{ name: '获取省市区列表',method: 'getProvs', path: 'm2c.support/regn/provs', type: 'get'},
{ name: '根据省id获取市列表',  method: 'getCitys', path: 'm2c.support/regn/cits', type: 'get'},
{ name: '根据市id获取区列表', method: 'getAreas', path: 'm2c.support/regn/areas', type: 'get'},
{ name: '获取业务员列表', method: 'getSeller', path: 'm2c.scm/seller/sys', type: 'get'},
{ name: '获取新增商家ID', method: 'getDealerId', path: 'm2c.scm/dealer/sys/id', type: 'get'},
{ name: '获取商家详情', method: 'getUserInfo',path: 'm2c.scm/dealer/sys/',type: 'get'},
{ name: '获取管理员列表', method: 'userInfoShow', path: 'm2c.users/user/listForUserUnbind', type: 'get'},
{ name: '提交新增绑定管理员', method: 'addManager', path: 'm2c.users/user/add', type: 'post'},
{ name: '提交商家', method: 'dealerModify',path: 'm2c.scm/dealer/sys/mng'},
{ name: '商品分类', method: 'goodsLevel', path: 'm2c.scm/goods/classify/level',type:'get'},
{ name: '获取订单列表', method: 'getOrderList', path: 'm2c.scm/order/manager/orderList',type:'get'},
{ name: '获取售后单列表', method: 'getAfterOrderList',path: 'm2c.scm/aftersellorder/manager/aftersellorderlist',type:'get'},
{ name: '查询特惠价列表信息',  method: 'getSpecialPriceList',  path: 'm2c.scm/goods/special/list',type: 'get'},
{ name: '终止特惠价', method: 'postSpecialPriceEnd',path: 'm2c.scm/goods/special/mng/end',type: 'post'},
{ name: '获取特惠价详情', method: 'getSpecialPriceInfo',path: 'm2c.scm/goods/special',type: 'get'},
{ name: '获取可选商品', method: 'getRecognized',path: 'm2c.scm/goods/choice/recognized',type: 'get'},
{ name: '获取特惠活动ID', method: 'getSpecialId',path: 'm2c.scm/goods/special/id',type: 'get'},
{ name: '提交保存特惠活动', method: 'postSpecial',path: 'm2c.scm/goods/special/mng'},  
{ name: '获取订单详情',   method: 'getDealerOrderInfo',path: 'm2c.scm/order/dealer/orderdetail',type:'get'},
{ name: '获取媒体详情', method: 'getMediaResInfo',path: 'm2c.media/mres/byIdList/mu',type:'get'},
{ name: '获取发货详情', method: 'getExpressDetail',path: 'm2c.scm/order/dealer/expressDetail',type:'get'},
{ name: '获取操作记录 订单详情', method: 'getOrderLogs',path: 'm2c.scm/order/logs/',type:'get'},
{ name: '获取操作记录 操作人信息', method: 'getUserInfoByIds',path: 'm2c.users/user/getUserInfoByIds',type:'get'},
{ name: '商品列表', method: 'getGoodsList',path: 'm2c.scm/goods',type:'get'},
{ name: '商品审核列表', method: 'getGoodsApproveList',path: 'm2c.scm/goods/approve',type:'get'},
//媒体平台调用
{ name: '商家列表',  method: 'dealerInformation',path: 'm2c.scm/dealer-out/information',type:'get'},
//媒体平台调用
{ name: '商品列表', method: 'goodsInformation',path: 'm2c.scm/goods/information',type:'get'},
{ name: '获取识别图', method: 'recognizeds', path: 'm2c.scm/goods/recognizeds',type:'get'},
{ name: '保存识别图', method: 'adminGoodsRecognizeds',path: 'm2c.scm/admin/goods/recognized', type:'get'},
{ name: '删除商品评论', method: 'delGoodsComment',path: 'm2c.scm/goods/comment/mng',type: 'delete'},
{ name: '查询商品评论列表',method: 'getGoodsComment',path: 'm2c.scm/goods/comment',type: 'get'},
{ name: '商品批量上架', method: 'goodsUpShelfBatch',path: 'm2c.scm/admin/goods/up/shelfbatch',type: 'put'},
{ name: '商品批量下架',method: 'goodsOffShelfBatch', path: 'm2c.scm/admin/goods/off/shelfbatch',type: 'put'},
{ name: '商品审核批量同意',method: 'goodsApproveAgreeBatch',path: 'm2c.scm/admin/goods/approve/agreebatch',type: 'post'},
{ name: '商品审核批量拒绝', method: 'goodsApproveRejectBatch', path: 'm2c.scm/admin/goods/approve/rejectbatch',type: 'post'},
{ name: '商品审核拒绝', method: 'goodsApproveReject', path: 'm2c.scm/goods/approve/mng/reject', type: 'post'},
{ name: '商品分类树',method: 'goodsClassifyTree',path: 'm2c.scm/goods/classify/tree',type: 'get'},
{ name: '商品删除', method: 'goodsDelete',path: 'm2c.scm/goods/', type: 'delete'},
{ name: '商品下架',method: 'goodsOffShelf', path: 'm2c.scm/goods/mng/off/shelf/',type: 'put'},
{ name: '商品上架',method: 'goodsUpShelf',path: 'm2c.scm/goods/mng/up/shelf/',type: 'put'},
{ name: '商品审核同意',method: 'goodsApproveAgree', path: 'm2c.scm/goods/approve/mng/agree',type: 'post'},
{ name: '查询商品详情', method: 'getGoodsDetail', path: 'm2c.scm/goods/',type: 'get'},
{ name: '查询商品审核详情', method: 'getGoodsApproveDetail', path: 'm2c.scm/goods/approve/', type: 'get'},
{ name: '商品历史记录详情',    method: 'getGoodsInfoHistory', type: 'get'},
{ name: '查询售后单详情', method: 'loadOrderDetail', path: 'm2c.scm/dealerorderafter/dealerorderafterselldetail',type: 'get'},
{ name: '查询售后操作列表',method: 'getOperatingRecord', path: 'm2c.scm/order/logs/res',type: 'get'},
{ name: '查询售后物流信息', method: 'getAftreselllogistics', path: 'm2c.scm/aftersellorder/manager/aftreselllogistics', type: 'get'},
//aftreselllogistics
{ name: '查询结算列表', method: 'getCountQueryList', path: 'm2c.trading/web/settle/dealer/admin/pager.web', type: 'get'},
{ name: '提交保存特惠活动', method: 'postSpecial', path: 'm2c.scm/goods/special/mng'},
{ name: '查询物流信息', method: 'getQueryExpress', path: 'm2c.scm/order/expressInfo', type: 'get'},
{ name: '查询结算详情', method: 'getCountQueryDetail', path: 'm2c.trading/web/settle/dealer/admin/detail.web', type: 'get'},
 // 首页
{ name: '获取商家数量', method: 'getDealerNum',path: 'm2c.scm/admin/dealer/report/dealer/total',type: 'get'},
{ name: '获取在售商品数量',   method: 'getGoodsNum', path: 'm2c.scm/admin/goods/for/sale/num', type: 'get' },
{ name: '获取销售金额',  method: 'getSellMoney', path: 'm2c.scm/admin/dealer/report/this/month/sell/money', type: 'get'},
{ name: '获取今日或昨日数据', method: 'getReportData', path: 'm2c.scm/admin/dealer/report/day', type: 'get'},
{ name: '获取商家销售榜',  method: 'getDataList',  path: 'm2c.scm/admin/dealer/report/month/sell/top', type: 'get' },
{ name: '获取7日数据折线图',   method: 'getReportDataList', path: 'm2c.scm/admin/dealer/report/7/days/sell/money', type: 'get'},
{ name: '获取国家列表',  method: 'getIntel',  path: 'm2c.operate/address/getintel.web', type: 'get'},
{ name: '获取品牌详情', method: 'getBrand', path: 'm2c.scm/brand', type: 'get'},
{ name: '获取品牌审核详情', method: 'getApprove', path: 'm2c.scm/brand/approve',type: 'get'},
{ name: '获取新增品牌ID', method: 'getBandId', path: 'm2c.scm/brand/id',type: 'get'},
{ name: '上传图片', method: 'uploadImg', path: 'm2c.support/img/upload', type: 'post'},
{ name: '品牌批量审核通过', method: 'batchagree', path: 'm2c.scm/admin/brand/approve/batchagree', type: 'post' },
{ name: '品牌审核通过', method: 'approveAgree', path: 'm2c.scm/brand/approve/mng/agree', type: 'post' },
{ name: '品牌批量审核拒绝', method: 'batchreject', path: 'm2c.scm/admin/brand/approve/batchreject',type: 'post'},
{ name: '品牌审核拒绝', method: 'approveReject', path: 'm2c.scm/brand/approve/mng/reject', type: 'post' },
{ name: '品牌添加或修改',  method: 'modifyBrand', path: 'm2c.scm/brand/mng'},
{ name: '删除品牌', method: 'deleteBrand', path: 'm2c.scm/brand/mng', type: 'delete'},
{ name: '获取品牌列表', method: 'getBrandList',path: 'm2c.scm/brand', type: 'get'},
{ name: '获取品牌审核列表',  method: 'getBrandApproveList', path: 'm2c.scm/brand/approve'},
//  设置模块
{ name: '获取商品分类列表（树结构）',  method: 'getGoodsClassifyTree', path: 'm2c.scm/goods/classify/tree', type: 'get'},
//  设置模块分类 渲染下拉框
{ name: '获取商品二级分类列表',  method: 'getGoodsSecondClassifyTree', path: 'm2c.scm/goods/classify/level?level=2', type: 'get'},
//  设置模块
{ name: '删除商品分类',  method: 'deleteClassify', path: 'm2c.scm/goods/classify/mng',type: 'delete' },
{ name: '商品分类未设置费率查询', method: 'queryRate', path: 'm2c.scm/goods/classify/service/rate/is/null',type: 'get'},
{ name: '保存商品分类修改', method: 'saveClassifyModify',type: 'put'},
{ name: '新增提交保存',  method: 'saveAddClassify',path: 'm2c.scm/goods/classify/mng',type: 'post'},
{ name: '保存商品费率',  method: 'changeRateYes',path: 'm2c.scm/goods/classify/mng/', type:'put'},
{ name: '获取计量单位列表', method: 'getUnitList', path: 'm2c.scm/unit',type: 'get'},
{ name: '获取单位Id',  method: 'getUnitId',path: 'm2c.scm/unit/id', type: 'get'},
{ name: '保存计量单位', method: 'changeUnitConfirm',path: 'm2c.scm/unit/mng'},
{ name: '删除计量单位',  method: 'deleteUnitConfirm', path: 'm2c.scm/unit/mng',type: 'delete'},
{ name: '获取规格列表',  method: 'getStantardList', path: 'm2c.scm/stantard',type: 'get'},
{ name: '获取规格Id',method: 'getStantardId',path: 'm2c.scm/stantard/id',type: 'get'},
{ name: '保存规格', method: 'changeStantardConfirm',path: 'm2c.scm/stantard/mng'},
{ name: '删除规格',  method: 'deleteStantardConfirm', path: 'm2c.scm/stantard/mng', type: 'delete'}
]
