import { 
    EleInput,
    EleTextarea,
    EleCheckbox,
    EleRadio,
    EleSelect,
    EleSwitch,
    EleCascader,
    EleDate,
    EleDateRange,
    EleDateYear,
    EleDateMonth,
    EleDateWeek,
    EleTime,
    EleTimeRange,
    EleTimeFixed,
    EleTimeFixedRange,
    EleDateTime,
    EleDateTimeRange,
    EleEditor,
    EleUpload,
    ListData,
    FormData } from '../components/'

export default{
    EleInput,
    EleTextarea,
    EleCheckbox,
    EleRadio,
    EleSelect,
    EleSwitch,
    EleCascader,
    EleDate,
    EleDateRange,
    EleDateYear,
    EleDateMonth,
    EleDateWeek,
    EleTime,
    EleTimeRange,
    EleTimeFixed,
    EleTimeFixedRange,
    EleDateTime,
    EleDateTimeRange,
    EleEditor,
    EleUpload,
    ListData,
    FormData
}